version: '3.9'
services:
  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=matcha
    ports:
    - '5432:5432'